name: mac

on:
  workflow_dispatch: 

jobs:
  build-and-pack:
    runs-on: macos-latest
    steps:
     - name: code
       run: |
         git clone "https://github.com/hhelibe2006-commits/zanshi.git"
         git lfs fetch
         git lfs checkout
         cd zanshi

     - name: python
       uses: actions/setup-python@v5
       with:
         python-version: '3.14.4'

     - name: install
       run: |
         pip install .
         file img_align_celeba.zip

     - name: yun
       run: |
         python data_preprocess.py
         python train.py
         python inference.py

     - name: img_aligen_celeba
       uses: actions/upload-artifact@v4
       with:
         name: data
         path: img_align_celeba/









